# Use postgres/password user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    ports:
      - 7000:7000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: jmticonap/api-product
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=PROD
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_HOSTNAME=localhost
      - DB_NAME=api_product_db
    ports:
      - 3000:3000
    network_mode: "host"